const styles: { [key: string]: React.CSSProperties } = {
  container: {
    minHeight: "100vh",
    width: "100vw",
    backgroundColor: "#121212",
    color: "#ffffff",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontFamily: "sans-serif",
    padding: "2rem",
  },

  contentWrapper: {
    width: "100%",
    maxWidth: "600px",
  },
  title: {
    fontSize: "1.75rem",
    marginBottom: "0.5rem",
    textAlign: "center",
  },
  description: {
    fontSize: "1.1rem",
    color: "#bbbbbb",
    textAlign: "center",
    marginBottom: "2rem",
  },
  sectionTitle: {
    marginTop: "2rem",
    fontSize: "1.3rem",
    marginBottom: "1rem",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
    backgroundColor: "#1e1e1e",
    padding: "1.5rem",
    borderRadius: "0.5rem",
    border: "1px solid #333",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    marginBottom: "1rem",
  },
  label: {
    marginBottom: "0.3rem",
    fontWeight: "bold",
  },
  select: {
    padding: "0.5rem",
    borderRadius: "0.3rem",
    backgroundColor: "#2a2a2a",
    color: "#fff",
    border: "1px solid #444",
  },
  input: {
    padding: "0.5rem",
    borderRadius: "0.3rem",
    backgroundColor: "#2a2a2a",
    color: "#fff",
    border: "1px solid #444",
  },
  submitButton: {
    padding: "12px 20px",
    fontSize: "16px",
    border: "none",
    borderRadius: "6px",
    backgroundColor: "#007bff",
    color: "#fff",
    cursor: "pointer",
    transition: "0.2s ease-in-out",
  },
  submitButtonDisabled: {
    backgroundColor: "#555",
    opacity: 0.6,
    cursor: "not-allowed",
  },
  logCard: {
    marginTop: "1rem",
    padding: "1rem",
    borderRadius: "0.5rem",
    backgroundColor: "#1e1e1e",
    border: "1px dashed #555",
    fontSize: "0.95rem",
    color: "#ccc",
  },
  walletCard: {
    marginBottom: "1rem",
    padding: "1rem",
    borderRadius: "0.5rem",
    backgroundColor: "#1e1e1e",
    border: "1px solid #444",
  },
  link: {
    display: "inline-block",
    marginBottom: "1rem",
    color: "#1976D2",
    textDecoration: "none",
    fontWeight: "bold",
  },
  inputWrapper: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  maxButton: {
    padding: "0.5rem 0.75rem",
    fontSize: "0.9rem",
    backgroundColor: "#333",
    color: "#fff",
    border: "1px solid #555",
    borderRadius: "4px",
    cursor: "pointer",
  },
  balanceText: {
    fontSize: "0.9rem",
    color: "#aaa",
    marginTop: "0.25rem",
  },
  infoText: {
    fontSize: "0.9rem",
    color: "#cccccc",
    marginTop: "1rem",
  },
  outputText: {
    fontSize: "1rem",
    color: "#00ff99",
    marginTop: "0.5rem",
  },
  loader: {
    border: "4px solid #f3f3f3",
    borderTop: "4px solid #3498db",
    width: "100%",
    height: "100%",
    animation: "spin 2s linear infinite",
  },
};

export default styles;
